Don't require individual tuple encapsulation in fontforge.font.bitmapSizes setter
Documentation specs that this should take the same format as
font.bitmapSizes returns: it doesn't;
  >>> f.bitmapSizes = ((1,), (2,))
yields
  >>> f.bitmapSizes
  (1, 2)

Which is fun, but what actually happens is the user gets
  >>> f.bitmapSizes = (1, 2)
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
  SystemError: new style getargs format but argument is not a tuple
and gives up.

Closes: #5137