Include scripting.h for DictionaryFree
The function `DictionaryFree` has been moved to `scripting.h` in commit
1e61ac0e1cfe44913f9f4bd0f879deaaaf77f08b.

This commit prevents the following warning

```
fontview.c: In function 'FontView_Free':
fontview.c:7567:5: warning: implicit declaration of function 'DictionaryFree'
                   [-Wimplicit-function-declaration]
     DictionaryFree(fv->b.fontvars);
```