Python API fails: font.size_feature (setter)
Fixed errors:

  Replaced Python2-correct usage of PyBytes_AsString() with the version
  compatibility macros PYGETSTR() and ENDPYGETSTR().  This fixed this
  error seen under Python 3 on second string of (lang,name) pair:
          TypeError: expected bytes, str found

  Checking for whether argument/sub-arguments were the expected tuple or
  list used the check for 'sequences'.  A string is also a sequence,
  making for strange error messages on user goofs.  Changed to check more
  specifically for list or tuple types.

Other changes:

  Improved some error messages from problems with user calling arguments.

  Desire was to allow caller to request that the 'size' value should be
  deleted.  Apparently the existing coded check was only for use of
        del font.size_feature
  Added ability to say
        font.size_feature = None

  Added Py_DECREF()s to pair with PySequence_GetItem() calls as documented
  by Python, but unfortunately not everyplace needed in this code.

However, this GPOS 'size' feature apparently had little industry acceptance,
and so problems with it was likely not a problem...?