Fix webcollab.py to be more Python3 compatible
Change c3770c88b50 introduced a new python source file, webcollab.py,
containing some print statements, a well-known incompatibility at the
source level between Python 2 and Python 3.

Starting an updated fontforge built with Python 3 produces this error:

  File "/home/tom/local/share/fontforge/python/webcollab.py", line 39
    print 'webcollab closing...'
                               ^
SyntaxError: invalid syntax

This fix merely changes to the Python 3 function call format for print.
It seems to satisfy both Python3 and Python2...