Python 3 compatibility error: font.printSample()
In FontForge built with Python 3, script API font.printSample() would
reject calls displaying error messages such as:
      TypeError: expected bytes, str found
for any of the arguments accepting strings - the initial, third and
fourth arguments.

This problem not seen running FontForge built with Python 2.

The code had never been converted to be compatible with Python 3, and
was still using PyBytes_* routines to handle strings.  Changed to use
PyArg_ParseTuple() to handle required and optional arguments, while
checking argument types and counts.

Fixed a small gotcha about for reference counting and the use of
PySequence_GetItem().  Also improved the user-directed error messages
for problems with input arguments.

Thoroughly tested with all variations on argument types and counts.
(~280 lines of Python code to test API signature)