PyMODINIT_FUNC requires external linkage on Windows (dllexport)
python.c:17919:23: error: external linkage required for symbol 'CreatePyModule_ff_internals' because of 'dllexport' attribute